"""Initial database schema

Revision ID: c2059c8af30a
Revises: 
Create Date: 2026-09-23 11:53:26.557688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2059c8af30a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Events',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('Title', sa.String(length=200), nullable=False),
    sa.Column('Description', sa.String(length=5000), nullable=False),
    sa.Column('Category', sa.String(length=100), nullable=False),
    sa.Column('Location', sa.String(length=200), nullable=False),
    sa.Column('Start_Date', sa.DateTime(), nullable=False),
    sa.Column('End_Date', sa.DateTime(), nullable=False),
    sa.Column('Organiser', sa.String(length=200), nullable=False),
    sa.Column('Image', sa.String(length=2000), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_Events_Category'), 'Events', ['Category'], unique=False)
    op.create_index(op.f('ix_Events_Start_Date'), 'Events', ['Start_Date'], unique=False)
    op.create_table('Users',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('Username', sa.String(length=200), nullable=False),
    sa.Column('Email', sa.String(length=200), nullable=False),
    sa.Column('Password', sa.String(length=500), nullable=False),
    sa.Column('Bio', sa.String(length=2000), nullable=True),
    sa.Column('DP', sa.String(length=2000), nullable=True),
    sa.Column('Token_Version', sa.Integer(), server_default='0', nullable=False),
    sa.Column('Created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_Users_Email'), 'Users', ['Email'], unique=True)
    op.create_table('Posts',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('Title', sa.String(length=200), nullable=False),
    sa.Column('Content', sa.String(length=5000), nullable=False),
    sa.Column('Location', sa.String(length=200), nullable=True),
    sa.Column('Author_ID', sa.Integer(), nullable=False),
    sa.Column('Created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['Author_ID'], ['Users.ID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_Posts_Author_ID'), 'Posts', ['Author_ID'], unique=False)
    op.create_table('Saved_Events',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('User_ID', sa.Integer(), nullable=False),
    sa.Column('Event_ID', sa.Integer(), nullable=False),
    sa.Column('Saved_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['Event_ID'], ['Events.ID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['User_ID'], ['Users.ID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('User_ID', 'Event_ID', name='unique_saved_event')
    )
    op.create_table('Liked_Posts',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('Post_ID', sa.Integer(), nullable=False),
    sa.Column('User_ID', sa.Integer(), nullable=False),
    sa.Column('Liked_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['Post_ID'], ['Posts.ID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['User_ID'], ['Users.ID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('Post_ID', 'User_ID', name='unique_liked_post')
    )
    op.create_index(op.f('ix_Liked_Posts_User_ID'), 'Liked_Posts', ['User_ID'], unique=False)
    op.create_table('Saved_Posts',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('User_ID', sa.Integer(), nullable=False),
    sa.Column('Post_ID', sa.Integer(), nullable=False),
    sa.Column('Saved_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['Post_ID'], ['Posts.ID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['User_ID'], ['Users.ID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('User_ID', 'Post_ID', name='unique_saved_post')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Saved_Posts')
    op.drop_index(op.f('ix_Liked_Posts_User_ID'), table_name='Liked_Posts')
    op.drop_table('Liked_Posts')
    op.drop_table('Saved_Events')
    op.drop_index(op.f('ix_Posts_Author_ID'), table_name='Posts')
    op.drop_table('Posts')
    op.drop_index(op.f('ix_Users_Email'), table_name='Users')
    op.drop_table('Users')
    op.drop_index(op.f('ix_Events_Start_Date'), table_name='Events')
    op.drop_index(op.f('ix_Events_Category'), table_name='Events')
    op.drop_table('Events')
    # ### end Alembic commands ###
